[package]
name = "rust-apps"
version = "0.1.0"
authors = ["Derrick McKee <derrick.mckee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

libc = "0.2.5"
rand = "0.7.2"